services:
  db:
    image: postgres:16-alpine
    container_name: choisein-db
    environment:
      POSTGRES_DB: INchoice
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 21032007A
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d INchoice"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: choisein-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/INchoice
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: 21032007A
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data:
